"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import Image from "next/image";

const base=process.env.NEXT_PUBLIC_REPORT_BASE_PATH??"";
const asset=(x:string)=>`${base}/${x}`;
const slides=[
["title","Title"],["why","Why this session"],["loop","The loop"],["terminal","The terminal"],["first","First commands"],["moving","Moving around"],["reading","Reading files"],["safety","Staying safe"],["running","Running a project"],["errors","Reading errors"],["git","Git in one picture"],["shipping","Shipping"],["undo","Undo safely"],["agent","The coding agent"],["today","Today's build"],["next","What's next"]] as const;

export default function Home(){
 const ref=useRef<HTMLElement>(null); const[a,setA]=useState(0); const[menu,setMenu]=useState(false);
 const progress=useMemo(()=>`${((a+1)/slides.length)*100}%`,[a]);
 useEffect(()=>{const s=ref.current;if(!s)return;const p=Array.from(s.querySelectorAll<HTMLElement>("[data-story-panel]"));const f=()=>{const vertical=getComputedStyle(s).flexDirection==="column";const r=s.getBoundingClientRect();const o=vertical?r.top:r.left;setA(p.reduce((b,x,i)=>{const xr=x.getBoundingClientRect(),br=p[b].getBoundingClientRect();const xp=vertical?xr.top:xr.left,bp=vertical?br.top:br.left;return Math.abs(xp-o)<Math.abs(bp-o)?i:b},0))};f();s.addEventListener("scroll",f,{passive:true});return()=>s.removeEventListener("scroll",f)},[]);
 const go=(i:number)=>{document.getElementById(slides[Math.max(0,Math.min(slides.length-1,i))][0])?.scrollIntoView({behavior:"smooth",inline:"start"});setMenu(false)};
 return <div className="report-shell"><div className="read-progress"><span style={{width:progress}}/></div><header className="topbar"><button className="noise-mark" onClick={()=>go(0)} aria-label="Go to title"><Image src={asset("noise-logo-black.png")} alt="Noise Media" width={1920} height={830} unoptimized/></button><div className="report-name"><span>Noise ×</span><strong>Zero to Build</strong></div><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-label="Open slide menu"><i/><i/><i/></button></header><aside className={`chapter-nav ${menu?"open":""}`}><p>Jump to slide</p><nav>{slides.map((x,i)=><button key={x[0]} className={a===i?"active":""} onClick={()=>go(i)}><span>{String(i+1).padStart(2,"0")}</span>{x[1]}</button>)}</nav></aside><main className="horizontal-story" ref={ref} aria-label="Zero to build: vibe coding in the terminal - Noise technical tutorials session one">

<S id="title" dark><div className="thank-you-main"><p className="thank-kicker">Noise technical tutorials · session 01</p><h1>Zero to build: vibe coding in the terminal.</h1><p className="title-period">Walk in with no coding experience. Leave with a platform of your own</p></div><Foot>01 / 16</Foot></S>

<S id="why"><H n="02" e="Why this session exists" t="You already do the hard part." p="The valuable skill in product work is deciding what should exist, spotting what feels wrong, and giving clear direction. The team does that every day. This session adds the hands-on part."/><div className="month-points"><Card n="01" t="You decide what should exist">That judgement is the job. The tools in this session exist to serve it, not replace it.</Card><Card n="02" t="You spot what feels wrong">Today you learn to open the bonnet and find where the feeling comes from: the file, the line, the error.</Card><Card n="03" t="You give clear direction">A good brief is already most of the work. By the close you will brief a coding agent the way you brief anyone else.</Card></div><Call l="What today adds">Enough hands-on skill to inspect a project, make a bounded change, understand what a coding agent is doing, and review work before it ships.</Call></S>

<S id="loop"><H n="03" e="The map for everything that follows" t="One loop runs through the whole session." p="Every tool today is a different way of moving around the same loop. Learn the loop and the commands become details you can look up."/><div className="month-points"><Card n="01" t="Orient">Where am I, what is this project, what state is it in?</Card><Card n="02" t="Inspect">Read before you touch. Files, scripts, errors, diffs.</Card><Card n="03" t="Change">The smallest useful change, in a safe place.</Card></div><div className="month-points"><Card n="04" t="Test">Run the project's own checks, then a manual look.</Card><Card n="05" t="Review">Read the actual diff. Understand every line or ask.</Card><Card n="06" t="Ship">A deliberate decision, then verify the live result.</Card></div><Call l="The aim">Not to memorise commands. To recognise the loop: orient, inspect, change, test, review, ship.</Call></S>

<S id="terminal"><H n="04" e="First: what the terminal even is" t="A text conversation with your computer." p="The terminal is a text interface. It always has a current location, called the working directory, and every command you type runs from that location. Six words cover most of what you will hear today."/><div className="detail-grid cols-3"><Metric l="Directory" v="Folder" p="same thing, older name"/><Metric l="Path" v="Address" p="where a file or folder lives"/><Metric l="Repo" v="Project" p="a folder of work tracked by Git"/><Metric l="Command" v="Instruction" p="runs from where you are"/><Metric l="Process" v="Program" p="something running, like a local server"/><Metric l="Exit code" v="Result" p="zero usually means it worked"/></div><Call l="Why this matters">Every error message, every agent answer, every deploy log uses these six words. Once they are plain, the rest of the day stops being jargon.</Call></S>

<S id="first"><H n="05" e="Try it now" t="Your first three commands." p="Open a terminal and run one command at a time, exactly as shown. Press the button below the window to walk through what you will see."/><div className="split-try"><Term title="Terminal" steps={[
{cmd:"pwd",out:["/Users/you/projects"]},
{cmd:"ls",out:["platform\t\tnotes.txt\t\tphotos"]},
{cmd:"ls -la",out:["total 6","drwxr-xr-x  5 you  staff  160 30 Sep 09:41 .","drwxr-xr-x  9 you  staff  288 30 Sep 09:40 ..","drwxr-xr-x  6 you  staff  192 30 Sep 09:41 platform","-rw-r--r--  1 you  staff   42 30 Sep 09:41 notes.txt"]}
]}/><div className="try-notes"><article><span>WHAT EACH ONE ANSWERS</span><ul><li><b>pwd</b> - where am I right now?</li><li><b>ls</b> - what is here?</li><li><b>ls -la</b> - the same, including hidden files and detail.</li></ul></article><article><span>THE HABIT</span><p>Orientation before action. Every session, every task, every time you come back to a project: where am I, what is here.</p></article></div></div></S>

<S id="moving"><H n="06" e="Getting around" t="Moving is one verb: cd." p="cd changes the working directory. Everything else is a shortcut on top of it."/><div className="happens-grid"><Phase l="THE MOVES" rows={["cd platform - enter a folder by name","cd .. - step up to the parent","cd - - jump back to where you were","pwd after every move, until it is second nature"]}/><Phase l="THE SHORTCUTS" rows={["Tab completes paths - faster and avoids typos","Quote paths with spaces: cd \"My Projects/platform\"","A path is just an address: absolute from the root, relative from here"]}/><Phase l="TRY IT: FIND THE PROJECT" rows={["pwd to name your starting point","ls each level, cd into the project","Confirm it is a code project: package.json","Confirm Git tracks it: a hidden .git in ls -la"]}/></div><Call l="Success check">You can say where the project lives and name the two things that identify it: package.json and .git.</Call></S>

<S id="reading"><H n="07" e="Looking without touching" t="Reading is a skill of its own." p="Most of today is reading: files, search results, errors, diffs. None of these commands change anything."/><div className="happens-grid"><Phase l="READ A FILE" rows={["cat package.json - print a short file","less package.json - page a long one, q to quit","head -40 and tail -40 - the start or the end"]}/><Phase l="SEARCH THE PROJECT" rows={["grep -R \"word\" . - find every mention","rg \"word\" - the faster, cleaner version","Results come as file:line:match"]}/><Phase l="HOW TO READ RESULTS" rows={["A search result is a map, not a verdict","Open the surrounding code before deciding what it does","Note the real file paths - you will need them for every brief you write later"]}/></div><Call l="Why this matters">package.json is the project's command menu. Reading it before running anything is safer than copying a command from another project.</Call></S>

<S id="safety"><H n="08" e="The one rule that keeps you safe" t="Some commands you stop and check." p="Everything so far only reads. A small set of commands change or delete things, and they deserve a pause every single time."/><div className="happens-grid"><Phase l="STOP AND CHECK" rows={["rm and rm -rf - delete, no undo","sudo - act as the computer's owner","Anything with > - replaces a file's contents","force, reset, migration - words that mean permanent"]}/><Phase l="THE PAUSE" rows={["Say out loud what exact path or system it will change","Not sure? Do not run it. Ask first.","Delete only inside your own practice folder while learning"]}/><Phase l="NEVER PASTE" rows={["Passwords, API keys, tokens","Client or customer data","Anything secret - into a terminal, a prompt, or a chat with an agent"]}/></div><Call l="The safe practice rule">Learn on a local copy or a disposable practice folder, never on production, never straight onto the main branch.</Call></S>

<S id="running"><H n="09" e="Running a real project" t="package.json is the command menu." p="Every project lists its own commands in the scripts section of package.json. Read them first, then run them by name. Walk through a typical start below."/><div className="split-try"><Term title="Terminal - inside the project" steps={[
{cmd:"npm ci",out:["added 214 packages in 6s"]},
{cmd:"npm run dev",out:["","> platform@0.1.0 dev","  VITE v7 ready in 412 ms","","  ➜  Local:   http://localhost:5173/"]},
{cmd:"(open http://localhost:5173 in your browser)",out:["Your project, running on your machine. Nobody else's."]},
{cmd:"Ctrl+C",out:["Server stopped. The terminal is yours again."]}
]}/><div className="try-notes"><article><span>WHILE IT RUNS</span><ul><li>The dev server occupies that terminal - open a second tab for anything else</li><li>Change a file, save, and the browser updates itself</li><li>Ctrl+C stops the server cleanly</li></ul></article><article><span>THE HABIT</span><p>Read the scripts section before running anything. The names vary project to project; the menu is always package.json.</p></article></div></div></S>

<S id="errors"><H n="10" e="When something breaks" t="An error is a location, not a failure." p="Read from the bottom up, looking for the first line that names your code. Then answer four questions and you have a bug note anyone - or any agent - can act on."/><div className="split-try"><Term title="Terminal - a failing build" steps={[
{cmd:"npm run build",out:["","> platform@0.1.0 build","  vike v0.4 build","","src/App.tsx:12:23 - error TS2552:","Cannot find name 'titlle'. Did you mean 'title'?","","build failed"]}
]}/><div className="try-notes"><article><span>THE FOUR QUESTIONS</span><ul><li>What failed? The build.</li><li>Where? src/App.tsx, line 12.</li><li>Why? A name is misspelled.</li><li>What changed just before? That is usually the cause.</li></ul></article><article><span>YOUR BUG NOTE</span><p>Command: npm run build. Result: failed. First useful error: src/App.tsx:12 - Cannot find name 'titlle'. Last change: edited the hero heading. Expected: build passes. That note is the whole handoff.</p></article></div></div></S>

<S id="git"><H n="11" e="Git in one picture" t="Five nouns, one flow." p="Git separates your work into five places. Changes move left to right, and you choose when each move happens."/><div className="gitflow"><article><span>1</span><strong>Working tree</strong><p>the files as they are right now</p></article><i>→</i><article><span>2</span><strong>Staging area</strong><p>the changes picked for the next save</p></article><i>→</i><article><span>3</span><strong>Commit</strong><p>a named snapshot of those changes</p></article><i>→</i><article><span>4</span><strong>Branch</strong><p>your own line of work, off main</p></article><i>→</i><article><span>5</span><strong>Remote</strong><p>the shared copy on GitHub</p></article></div><Call l="Why branches">A branch is a scratchpad with a name. Work there, get it reviewed, and main stays clean. A branch name should say what changes, not who is doing it.</Call></S>

<S id="shipping"><H n="12" e="The shipping loop" t="From an idea to a pull request." p="The same six commands, in the same order, every time. This is the loop from slide 3 with Git's names on it."/><div className="happens-grid"><Phase l="SET UP" rows={["git status - what state am I in?","git switch main && git pull - start fresh","git switch -c my-change - one branch, one outcome"]}/><Phase l="SAVE" rows={["git diff - read every change first","git add the specific files, never blindly","git commit -m \"what and why\""]}/><Phase l="SHARE" rows={["git push -u origin my-change","Open the pull request GitHub offers","PR says: what changed, what did not, how tested, risk"]}/></div><Call l="The key distinction">Opening a PR is review. Merging is a production action. They are separate decisions, and the second one is never automatic.</Call></S>

<S id="undo"><H n="13" e="Undo safely" t="Every mistake has a calm exit." p="Four situations cover almost everything that goes wrong. None of them involve force."/><div className="story-boxes"><Box l="Edited, want it back" v="git restore" p="Discards an uncommitted edit and restores the last committed version of that file."/><Box l="Staged the wrong file" v="--staged" p="git restore --staged unstages it but keeps your edit. Nothing lost."/><Box l="Inspect an old commit" v="git show" p="Reads a commit without changing your branch. Looking is always free."/><Box l="A shared commit is wrong" v="git revert" p="Adds a new commit that reverses it. History stays honest and shared."/></div><Call l="Never as a beginner">No force push, no hard reset, no rewriting history. If the state confuses you, save git status and git log --oneline -12 and ask for help with that exact picture.</Call></S>

<S id="agent"><H n="14" e="Where the coding agent fits" t="You brief it. You review it. You decide." p="A coding agent can inspect a repo, explain code, plan a change, edit files and run checks. Your job does not change: set the outcome and the boundaries, inspect the plan and the diff, decide whether the evidence is strong enough."/><div className="happens-grid"><Phase l="USUALLY SAFE TO APPROVE" rows={["Read files and search code","Run the project's own test and build scripts","Edit files on a feature branch","Show status and diff, explain errors"]}/><Phase l="PAUSE AND INSPECT" rows={["Install a new dependency","Change a database schema or run a migration","Send network requests","Push a branch or open a PR"]}/><Phase l="REFUSE UNTIL JUSTIFIED" rows={["Print or upload secrets","Read unrelated folders, use sudo, delete broad paths","Force-push shared history","Merge or deploy without your explicit decision"]}/></div><Call l="The working relationship">Not \"make it work\". It is: agree the outcome, inspect before edits, agree the scope, let it implement on a branch, make it run the checks, review the diff yourself, then decide.</Call></S>

<S id="today"><H n="15" e="Today's build" t="By the close, your own page, live at your own link." p="That is the promise of the session. Four stages, each one a thing you will physically do, with help in the room at every step."/><div className="story-boxes"><Box l="Stage one" v="Open + orient" p="Terminal open. pwd, ls, cd. Find the project, read its package.json, know where you are."/><Box l="Stage two" v="Run it" p="Install, start the dev server, open your own localhost address. Your project, on your machine."/><Box l="Stage three" v="Make it yours" p="One visible change: your name, your words, your colours. Save, watch the browser update."/><Box l="Stage four" v="Ship it" p="Branch, commit, push, PR, merge decision, and then the moment: your page, live, at a link you can send."/></div><Call l="Success check">You leave with a personalised platform of your own, and you can name every step that got it there.</Call></S>

<S id="next"><H n="16" e="What's next" t="This was session one of four." p="Each session stands alone but they build: today's loop is the same loop every later session runs on."/><div className="story-boxes"><Box l="Session 01 · today" v="Zero to build" p="Vibe coding in the terminal: orient, inspect, change, test, review, ship. Your own page, live."/><Box l="Session 02" v="Paid-ads build" p="Build, QA and report on a paid-ads workflow with the same loop and the same review discipline."/><Box l="Session 03" v="AI workflow" p="Build one repeatable AI workflow for your role, not a one-off prompt. Leave with it working."/><Box l="Session 04" v="Real data" p="Connect a platform to real data: spreadsheet or API in, live dashboard out."/></div><Thread>The loop you learned today is the one every later session runs on. You walked in with no coding experience. You leave with a platform of your own.</Thread></S>

</main><div className="slide-controls" aria-label="Deck navigation"><button aria-label="Previous panel" onClick={()=>go(a-1)} disabled={a===0}>← PREVIOUS</button><div><span>{slides[a][1]}</span><strong>{String(a+1).padStart(2,"0")} / {slides.length}</strong></div><button aria-label="Next panel" onClick={()=>go(a+1)} disabled={a===slides.length-1}>NEXT →</button></div></div>}

function S({id,children,dark=false}:{id:string;children:React.ReactNode;dark?:boolean}){return <section id={id} data-story-panel className={`story-panel ${dark?"title-panel thank-you-chapter":"light"}`}>{children}</section>}
function H({n,e,t,p}:{n:string;e:string;t:string;p:string}){return <header className="chapter-header insight-header"><div className="section-number">{n}</div><div><span className="eyebrow">{e}</span><h2>{t}</h2></div><p>{p}</p></header>}
function Card({n,t,children}:{n:string;t:string;children:React.ReactNode}){return <article><span>{n}</span><h3>{t}</h3><p>{children}</p></article>}
function Box({l,v,p}:{l:string;v:string;p:string}){return <article><span>{l}</span><strong>{v}</strong><p>{p}</p></article>}
function Metric({l,v,p}:{l:string;v:string;p:string}){return <article><span>{l}</span><strong>{v}</strong><b>{p}</b></article>}
function Phase({l,rows}:{l:string;rows:string[]}){return <article><span>{l}</span><ul>{rows.map(x=><li key={x}>{x}</li>)}</ul></article>}
function Thread({children}:{children:React.ReactNode}){return <div className="story-thread"><span>AND THEN</span><p>{children}</p></div>}
function Call({l,children}:{l:string;children:React.ReactNode}){return <div className="takeaway-bar"><span>{l}</span><p>{children}</p></div>}
function Foot({children}:{children:React.ReactNode}){return <div className="thank-foot"><span>Noise internal · technical tutorials</span><span>{children}</span></div>}

type TermStep={cmd:string;out:string[]};
function Term({title,steps}:{title:string;steps:TermStep[]}){
 const [n,setN]=useState(0);
 const done=n>=steps.length;
 return <div className="term"><div className="term-bar"><i/><i/><i/><span>{title}</span></div>
 <div className="term-body">
 {steps.slice(0,n).map((s,i)=><div key={i} className="term-step"><p className="term-cmd"><b>$</b> {s.cmd}</p>{s.out.map((o,j)=><p key={j} className="term-out">{o||"\u00a0"}</p>)}</div>)}
 {!done&&<button className="term-next" onClick={()=>setN(n+1)}>▸ type <code>{steps[n].cmd.length>28?steps[n].cmd.slice(0,28)+"…":steps[n].cmd}</code></button>}
 {done&&<button className="term-next replay" onClick={()=>setN(0)}>↺ replay</button>}
 </div></div>
}
