"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import Image from "next/image";

const base=process.env.NEXT_PUBLIC_REPORT_BASE_PATH??"";
const asset=(x:string)=>`${base}/${x}`;
const slides=[
["title","Title"],["why","Why this session"],["loop","The loop"],["terminal","The terminal, briefly"],["codex","Meet Codex"],["prompt","Your first prompt"],["watching","Watching it work"],["control","Staying in control"],["review","Reviewing the work"],["errors","When it breaks"],["git","Git in one picture"],["shipping","Shipping"],["undo","Undo safely"],["today","Today's build"],["craft","Briefing well"],["next","What's next"]] as const;

export default function Home(){
 const ref=useRef<HTMLElement>(null); const[a,setA]=useState(0); const[menu,setMenu]=useState(false);
 const progress=useMemo(()=>`${((a+1)/slides.length)*100}%`,[a]);
 useEffect(()=>{const s=ref.current;if(!s)return;const p=Array.from(s.querySelectorAll<HTMLElement>("[data-story-panel]"));const f=()=>{const vertical=getComputedStyle(s).flexDirection==="column";const r=s.getBoundingClientRect();const o=vertical?r.top:r.left;setA(p.reduce((b,x,i)=>{const xr=x.getBoundingClientRect(),br=p[b].getBoundingClientRect();const xp=vertical?xr.top:xr.left,bp=vertical?br.top:br.left;return Math.abs(xp-o)<Math.abs(bp-o)?i:b},0))};f();s.addEventListener("scroll",f,{passive:true});return()=>s.removeEventListener("scroll",f)},[]);
 const go=(i:number)=>{document.getElementById(slides[Math.max(0,Math.min(slides.length-1,i))][0])?.scrollIntoView({behavior:"smooth",inline:"start"});setMenu(false)};
 return <div className="report-shell"><div className="read-progress"><span style={{width:progress}}/></div><header className="topbar"><button className="noise-mark" onClick={()=>go(0)} aria-label="Go to title"><Image src={asset("noise-logo-black.png")} alt="Noise Media" width={1920} height={830} unoptimized/></button><div className="report-name"><span>Noise ×</span><strong>Zero to Build</strong></div><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-label="Open slide menu"><i/><i/><i/></button></header><aside className={`chapter-nav ${menu?"open":""}`}><p>Jump to slide</p><nav>{slides.map((x,i)=><button key={x[0]} className={a===i?"active":""} onClick={()=>go(i)}><span>{String(i+1).padStart(2,"0")}</span>{x[1]}</button>)}</nav></aside><main className="horizontal-story" ref={ref} aria-label="Zero to build: vibe coding in the terminal - Noise technical tutorials session one">

<S id="title" dark><div className="thank-you-main"><p className="thank-kicker">Noise technical tutorials · session 01</p><h1>Zero to build: vibe coding in the terminal.</h1><p className="title-period">Walk in with no coding experience. Leave with a platform of your own</p></div><Foot>01 / 16</Foot></S>

<S id="why"><H n="02" e="Why this session exists" t="You already do the hard part." p="The valuable skill in product work is deciding what should exist, spotting what feels wrong, and giving clear direction. The team does that every day. What changed: a coding agent now does the typing."/><div className="month-points"><Card n="01" t="You decide what should exist">That judgement is the job. The agent in this session exists to serve it, not replace it.</Card><Card n="02" t="You spot what feels wrong">Today you learn to say where the feeling comes from, and hand the fix to the agent with evidence.</Card><Card n="03" t="You give clear direction">A good brief was always most of the work. Now the brief is the whole job: the agent builds what you describe.</Card></div><Call l="What today adds">Enough hands-on practice to drive a coding agent in the terminal: install it, prompt it, watch it work, review what it did, and ship a platform of your own.</Call></S>

<S id="loop"><H n="03" e="The map for everything that follows" t="One loop runs through the whole session." p="You and the agent share six steps. Notice who does what: the agent reads, edits and runs; you brief, review and decide."/><div className="month-points"><Card n="01" t="Brief - you">Say the outcome and the boundaries in plain words.</Card><Card n="02" t="Orient - agent">It reads the project before touching anything.</Card><Card n="03" t="Change - agent">The smallest useful change, on its own branch of work.</Card></div><div className="month-points"><Card n="04" t="Test - agent">It runs the project's own checks and reports the result.</Card><Card n="05" t="Review - you">Read what actually changed. Understand it or ask.</Card><Card n="06" t="Ship - you">A deliberate decision, then verify the live result.</Card></div><Call l="The aim">Not to memorise commands. To run the loop: brief, orient, change, test, review, ship.</Call></S>

<S id="terminal"><H n="04" e="Five minutes of plumbing" t="Just enough terminal to point Codex at a folder." p="Codex lives in the terminal and works on the folder you are standing in. So you need exactly three moves before you meet it."/><div className="detail-grid cols-3"><Metric l="pwd" v="Where am I" p="prints your current folder"/><Metric l="ls" v="What is here" p="lists what the folder holds"/><Metric l="cd name" v="Move" p="steps into a folder; cd .. steps back"/><Metric l="Directory" v="Folder" p="same thing, older name"/><Metric l="Path" v="Address" p="where a file or folder lives"/><Metric l="Repo" v="Project" p="a folder of work tracked by Git"/></div><Call l="Why only this">Every other command today, Codex types for you. Your job is to stand in the right folder and know it - orientation before action, every session.</Call></S>

<S id="codex"><H n="05" e="Meet Codex" t="A coding agent that works on your machine." p="Codex CLI is OpenAI's coding agent. It runs locally, reads the project you point it at, edits files and runs the project's own tools. Install it once, sign in with ChatGPT, and it is ready. Walk through it below."/><div className="split-try"><Term title="Terminal" steps={[
{c:"npm install -g @openai/codex",out:["added 1 package in 4s"]},
{c:"cd projects && codex",out:[{ai:"Welcome to Codex CLI"},{ai:"Sign in with ChatGPT to use your plan"},{ai:"Signed in. Ready in ~/projects"}]},
{done:"Codex is installed, signed in, and waiting for plain words."}
]}/><div className="try-notes"><article><span>WHAT JUST HAPPENED</span><ul><li><b>npm install -g</b> - installs Codex once, for every project</li><li><b>codex</b> - opens the agent in the folder you are in</li><li><b>Sign in with ChatGPT</b> - your work plan covers it, no new account</li></ul></article><article><span>THE HABIT</span><p>cd into the project first, then run codex. Where you stand is what it works on.</p></article></div></div></S>

<S id="prompt"><H n="06" e="The moment this gets real" t="Your first prompt builds your first page." p="No syntax, no setup, no copying code from a tutorial. One clear sentence about what should exist. Press through a real first session below."/><div className="split-try"><Term title="Codex - your first build" steps={[
{ask:"Build me a personal page: my name, my role, and three things I love. One HTML file. Make it feel like me.",out:[{ai:"Plan: one index.html - your details, your words, clean styling"},{ai:"Created index.html (86 lines)"},{ai:"Run it: open index.html"}]},
{c:"open index.html",out:["Your browser opens. Your page. Built from one sentence."]},
{ask:"Make the background Noise orange and the type bigger.",out:[{ai:"Edited index.html (2 changes)"},{ai:"Refresh the browser to see it"}]},
{done:"Two prompts. Zero code typed. A page that is yours."}
]}/><div className="try-notes"><article><span>WHAT TO NOTICE</span><ul><li>You described an outcome, not steps</li><li>Codex said its plan before editing</li><li>You steered with a follow-up, in plain words</li></ul></article><article><span>THE HABIT</span><p>One bounded change per prompt. Small steps, reviewed often, beat one giant request.</p></article></div></div></S>

<S id="watching"><H n="07" e="While it works" t="Nothing happens in secret." p="Codex works in the open, in front of you. Learning to read its working is most of what confidence looks like."/><div className="happens-grid"><Phase l="WHAT YOU SEE" rows={["The plan, before it edits anything","Every file it reads and every change it makes","Every command it runs, with the result","A summary of what changed and why, at the end"]}/><Phase l="WHAT YOU CAN DO" rows={["Steer mid-turn: 'stop, keep the orange version'","Ask why: 'explain that change before you make it'","Say no to any step. It waits for you."]}/><Phase l="WHAT IT WILL NOT DO" rows={["Touch files outside your project without asking","Use the network without asking - it is off by default","Hide a command or its output"]}/></div><Call l="The posture">You are not watching a robot you hope behaves. You are directing a pair of hands that shows its work.</Call></S>

<S id="control"><H n="08" e="Staying in control" t="Approve, pause, refuse." p="Codex runs inside a sandbox: it can only write inside your project, and it must stop and ask before anything outside it. The /permissions command shows and changes the current mode."/><div className="happens-grid"><Phase l="USUALLY SAFE TO APPROVE" rows={["Read files and search code","Edit files inside the project","Run the project's own tests and build","Explain an error or a piece of code"]}/><Phase l="PAUSE AND INSPECT" rows={["Install a new dependency","Run a command you do not recognise","Send anything over the network","Push a branch or open a PR"]}/><Phase l="REFUSE UNTIL JUSTIFIED" rows={["Print or upload secrets - keys, tokens, passwords","Delete broad paths, use sudo, or force anything","Merge or deploy without your explicit decision"]}/></div><Call l="The one rule">It asks. You decide. If a request surprises you, the answer is no until you understand it - say out loud what it will change before you say yes.</Call></S>

<S id="review"><H n="09" e="After it works" t="Review is the skill." p="Codex summarises what it changed, and the summary is usually right. Your job is to check the claim against reality - which is exactly what review means everywhere else in the job."/><div className="happens-grid"><Phase l="READ ITS SUMMARY" rows={["What changed, file by file","What it ran to prove the change works","Anything it was unsure about"]}/><Phase l="CHECK THE TRUTH" rows={["git status - what files did it actually touch","git diff - the exact edits, line by line","Run it yourself: does the page or build behave"]}/><Phase l="ASK BEFORE SHIPPING" rows={["Explain this diff to me","What could this break","What did you not test"]}/></div><Call l="The standard">Do not ship what you cannot explain. Asking Codex to explain its own work counts - that is the review.</Call></S>

<S id="errors"><H n="10" e="When something breaks" t="An error is fuel for the agent." p="You do not fix errors in this workflow. You read the first useful line, hand it to Codex, and check the fix. Walk through it below."/><div className="split-try"><Term title="Codex - fixing a failure" steps={[
{c:"npm run build",out:["","> platform@0.1.0 build","","src/App.tsx:12:23 - error TS2552:","Cannot find name 'titlle'. Did you mean 'title'?","","build failed"]},
{ask:"The build fails: src/App.tsx line 12, Cannot find name 'titlle'. Fix it.",out:[{ai:"Found it - a typo in the hero heading"},{ai:"Edited src/App.tsx (1 line)"},{ai:"Ran npm run build - passes"}]},
{done:"You read the error. The agent fixed it. You verified."}
]}/><div className="try-notes"><article><span>YOUR PART IN THE FIX</span><ul><li>What failed? The build</li><li>Where? src/App.tsx, line 12</li><li>The exact first error line, pasted as-is</li></ul></article><article><span>THE HABIT</span><p>Read errors bottom-up for the first line that names your code. Hand that line over - never a shrug like "it's broken".</p></article></div></div></S>

<S id="git"><H n="11" e="Git in one picture" t="Your safety net, in five nouns." p="Git tracks every state of the project. Changes move left to right, and you choose when each move happens - which is what makes working with an agent safe."/><div className="gitflow"><article><span>1</span><strong>Working tree</strong><p>the files as they are right now</p></article><i>→</i><article><span>2</span><strong>Staging area</strong><p>the changes picked for the next save</p></article><i>→</i><article><span>3</span><strong>Commit</strong><p>a named snapshot of those changes</p></article><i>→</i><article><span>4</span><strong>Branch</strong><p>your own line of work, off main</p></article><i>→</i><article><span>5</span><strong>Remote</strong><p>the shared copy on GitHub</p></article></div><Call l="Why this matters with an agent">A commit before Codex starts and a commit after it finishes means every session is reversible. Codex can make the commits - you decide when.</Call></S>

<S id="shipping"><H n="12" e="Shipping" t="Codex can carry it to the door. You open the door." p="The agent can branch, commit, push and open the pull request. What it must never do on its own is the last step."/><div className="happens-grid"><Phase l="AGENT CAN DO" rows={["git switch -c my-change - a fresh branch","Commit with a message that says what and why","Push and open the PR","Write the PR: what changed, what did not, how tested"]}/><Phase l="YOU DO" rows={["Read the diff on the PR","Ask: what could this break","Decide: merge, change, or abandon"]}/><Phase l="THE KEY DISTINCTION" rows={["Opening a PR is review","Merging is a production action","They are separate decisions - the second is never the agent's"]}/></div><Call l="Then verify">After a merge, look at the live thing with your own eyes before you call it done. Every time.</Call></S>

<S id="undo"><H n="13" e="Undo safely" t="Every mistake has a calm exit." p="Four situations cover almost everything that goes wrong. None of them involve force, and Codex can run any of them for you."/><div className="story-boxes"><Box l="Edited, want it back" v="git restore" p="Discards an uncommitted edit and restores the last committed version of that file."/><Box l="Staged the wrong file" v="--staged" p="git restore --staged unstages it but keeps your edit. Nothing lost."/><Box l="Inspect an old commit" v="git show" p="Reads a commit without changing your branch. Looking is always free."/><Box l="A shared commit is wrong" v="git revert" p="Adds a new commit that reverses it. History stays honest and shared."/></div><Call l="Never as a beginner">No force push, no hard reset, no rewriting history. Confused? Save the state - git status and recent history - and ask for help with that exact picture.</Call></S>

<S id="today"><H n="14" e="Today's build" t="By the close, your own page, live at your own link." p="That is the promise of the session. Four stages, each one a thing you will physically do, with help in the room at every step."/><div className="story-boxes"><Box l="Stage one" v="Install + open" p="Terminal open. Install Codex, sign in, stand in a fresh folder. You are set up to build."/><Box l="Stage two" v="Prompt it" p="Describe your platform in plain words. Watch Codex plan it, build it, and show its work."/><Box l="Stage three" v="Make it yours" p="Steer with follow-ups: your name, your words, your colours. Review each change as it lands."/><Box l="Stage four" v="Ship it" p="Checkpoint, branch, PR, your merge decision - and then the moment: your page, live, at a link you can send."/></div><Call l="Success check">You leave with a personalised platform of your own, and you can name every step that got it there.</Call></S>

<S id="craft"><H n="15" e="The craft" t="Briefing well is the whole job." p="Everyone in this room already writes briefs for a living. These are the same muscles, aimed at an agent."/><div className="happens-grid"><Phase l="GOOD BRIEFS" rows={["Outcome, not steps: what exists when this is done","Boundaries: what must not change","One bounded change at a time","Evidence when reporting problems: the exact error line"]}/><Phase l="HABITS THAT PAY" rows={["Ask for the plan before the edits","Review every diff or ask it to explain","Commit before and after each task","Small steps, shipped often"]}/><Phase l="AS IT GROWS" rows={["AGENTS.md in the repo: your standing brief to the agent","codex resume picks up where a session left off","The loop never changes: brief, review, decide"]}/></div><Call l="The working relationship">Not "make it work". It is: agree the outcome, inspect the plan, let it build, review the evidence, then decide.</Call></S>

<S id="next"><H n="16" e="What's next" t="This was session one of four." p="Each session stands alone but they build: today's loop is the same loop every later session runs on, and Codex is on the team for all of them."/><div className="story-boxes"><Box l="Session 01 · today" v="Zero to build" p="Vibe coding in the terminal: brief, watch, review, ship. Your own page, live."/><Box l="Session 02" v="Paid-ads build" p="Build, QA and report on a paid-ads workflow with the same loop and the same review discipline."/><Box l="Session 03" v="AI workflow" p="Build one repeatable AI workflow for your role, not a one-off prompt. Leave with it working."/><Box l="Session 04" v="Real data" p="Connect a platform to real data: spreadsheet or API in, live dashboard out."/></div><Thread>The loop you learned today is the one every later session runs on. You walked in with no coding experience. You leave with a platform of your own.</Thread></S>

</main><div className="slide-controls" aria-label="Deck navigation"><button aria-label="Previous panel" onClick={()=>go(a-1)} disabled={a===0}>← PREVIOUS</button><div><span>{slides[a][1]}</span><strong>{String(a+1).padStart(2,"0")} / {slides.length}</strong></div><button aria-label="Next panel" onClick={()=>go(a+1)} disabled={a===slides.length-1}>NEXT →</button></div></div>}

function S({id,children,dark=false}:{id:string;children:React.ReactNode;dark?:boolean}){return <section id={id} data-story-panel className={`story-panel ${dark?"title-panel thank-you-chapter":"light"}`}>{children}</section>}
function H({n,e,t,p}:{n:string;e:string;t:string;p:string}){return <header className="chapter-header insight-header"><div className="section-number">{n}</div><div><span className="eyebrow">{e}</span><h2>{t}</h2></div><p>{p}</p></header>}
function Card({n,t,children}:{n:string;t:string;children:React.ReactNode}){return <article><span>{n}</span><h3>{t}</h3><p>{children}</p></article>}
function Box({l,v,p}:{l:string;v:string;p:string}){return <article><span>{l}</span><strong>{v}</strong><p>{p}</p></article>}
function Metric({l,v,p}:{l:string;v:string;p:string}){return <article><span>{l}</span><strong>{v}</strong><b>{p}</b></article>}
function Phase({l,rows}:{l:string;rows:string[]}){return <article><span>{l}</span><ul>{rows.map(x=><li key={x}>{x}</li>)}</ul></article>}
function Thread({children}:{children:React.ReactNode}){return <div className="story-thread"><span>AND THEN</span><p>{children}</p></div>}
function Call({l,children}:{l:string;children:React.ReactNode}){return <div className="takeaway-bar"><span>{l}</span><p>{children}</p></div>}
function Foot({children}:{children:React.ReactNode}){return <div className="thank-foot"><span>Noise internal · technical tutorials</span><span>{children}</span></div>}

type TermLine=string|{ai:string};
type TermStep={c?:string;ask?:string;done?:string;out?:TermLine[]};
function Term({title,steps}:{title:string;steps:TermStep[]}){
 const [n,setN]=useState(0);
 const done=n>=steps.length;
 const nextLabel=(s:TermStep)=>s.c?s.c.length>28?s.c.slice(0,28)+"…":s.c:s.ask?"your prompt":"finish";
 return <div className="term"><div className="term-bar"><i/><i/><i/><span>{title}</span></div>
 <div className="term-body">
 {steps.slice(0,n).map((s,i)=><div key={i} className="term-step">
  {s.c&&<p className="term-cmd"><b>$</b> {s.c}</p>}
  {s.ask&&<p className="term-ask"><b>you ›</b> {s.ask}</p>}
  {s.done&&<p className="term-done">{s.done}</p>}
  {(s.out||[]).map((o,j)=>typeof o==="string"?<p key={j} className="term-out">{o||"\u00a0"}</p>:<p key={j} className="term-ai"><b>codex ›</b> {o.ai}</p>)}
 </div>)}
 {!done&&<button className="term-next" onClick={()=>setN(n+1)}>▸ {steps[n].ask?"type ":steps[n].done?"finish":"type "}<code>{nextLabel(steps[n])}</code></button>}
 {done&&<button className="term-next replay" onClick={()=>setN(0)}>↺ replay</button>}
 </div></div>
}
